apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/buihai279/homelab-gitops/ts-demo
    newTag: c23eab9c75b43819003d00bc68e0add8812d3878
